services:

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      VITE_API_PROXY_TARGET: http://server:4000
    depends_on:
      - server
    volumes:
      - ./client:/client
      - /client/node_modules
    stdin_open: true
    tty: true

  server:
    build: ./server
    container_name: server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./server:/server
      - /server/node_modules
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http client:5173
    environment:
      NGROK_AUTHTOKEN: 343NCUHm2EHbtJhxrW9UX8mDvtf_3G5dv41j1XF5ooZZwGRpX
    ports:
      - "4040:4040"
    depends_on:
      - client

volumes:
  mongo_data:
