import { SchedulerJob } from "../models/schedulerJob.js";
import { DefenseCouncil } from "../models/defenseCouncil.js";
import { Project } from "../models/project.js";
import { executeSchedulerJob } from "../services/scheduler/schedulerService.js";

/**
 * Starts a background scheduling run using worker threads.
 * Route: POST /api/v1/admin/scheduler/jobs
 */
export const createSchedulerJob = async (req, res, next) => {
  const {
    projectIds = [],
    teacherIds = [],
    rooms = [],
    timeSlots = [],
    solverType = "genetic_algorithm",
    populationSize = 150,
    generations = 300
  } = req.body;

  try {
    if (projectIds.length === 0 || teacherIds.length === 0 || rooms.length === 0 || timeSlots.length === 0) {
      return res.status(400).json({
        success: false,
        message: "Must provide projectIds, teacherIds, rooms, and timeSlots."
      });
    }

    // 1. Create Job record in pending state
    const job = new SchedulerJob({
      config: {
        projectIds,
        teacherIds,
        rooms,
        timeSlots,
        solverType,
        populationSize,
        generations
      }
    });
    await job.save();

    // 2. Execute calculation in background worker thread (Non-blocking)
    // We do NOT await this promise so we can return HTTP 202 immediately.
    executeSchedulerJob(job._id).catch(err => {
      console.error(`Background solver job ${job._id} failed:`, err);
    });

    // 3. Return HTTP 202 Accepted (Standard Senior REST API Pattern)
    return res.status(202).json({
      success: true,
      message: "Automated scheduler execution started in background.",
      data: {
        jobId: job._id,
        status: job.status
      }
    });

  } catch (error) {
    next(error);
  }
};

/**
 * Checks the status and metrics of a scheduling run.
 * Route: GET /api/v1/admin/scheduler/jobs/:id
 */
export const getSchedulerJobStatus = async (req, res, next) => {
  try {
    const job = await SchedulerJob.findById(req.params.id)
      .populate("result.generatedCouncils");

    if (!job) {
      return res.status(404).json({
        success: false,
        message: "Scheduler job not found."
      });
    }

    return res.status(200).json({
      success: true,
      data: job
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Publishes the generated draft councils, making them visible to teachers and students.
 * Route: POST /api/v1/admin/scheduler/jobs/:id/apply
 */
export const applySchedulerJobResults = async (req, res, next) => {
  try {
    const job = await SchedulerJob.findById(req.params.id);
    if (!job) {
      return res.status(404).json({
        success: false,
        message: "Scheduler job not found."
      });
    }

    if (job.status !== "completed") {
      return res.status(400).json({
        success: false,
        message: `Cannot apply results. Job status is currently '${job.status}'.`
      });
    }

    const councilIds = job.result?.generatedCouncils || [];
    if (councilIds.length === 0) {
      return res.status(400).json({
        success: false,
        message: "No draft councils were generated by this job."
      });
    }

    // Publish all councils (set status to 'active')
    await DefenseCouncil.updateMany(
      { _id: { $in: councilIds } },
      { $set: { status: "active" } }
    );

    return res.status(200).json({
      success: true,
      message: `Successfully published ${councilIds.length} generated defense councils.`
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Discards all generated drafts and deletes the job run data.
 * Route: DELETE /api/v1/admin/scheduler/jobs/:id
 */
export const discardSchedulerJob = async (req, res, next) => {
  try {
    const job = await SchedulerJob.findById(req.params.id);
    if (!job) {
      return res.status(404).json({
        success: false,
        message: "Scheduler job not found."
      });
    }

    const councilIds = job.result?.generatedCouncils || [];

    // 1. Remove references on projects
    if (councilIds.length > 0) {
      await Project.updateMany(
        { councilId: { $in: councilIds } },
        { $set: { councilId: null, defenseStatus: "not_started" } }
      );

      // 2. Delete generated draft DefenseCouncil documents
      await DefenseCouncil.deleteMany({ _id: { $in: councilIds } });
    }

    // 3. Delete the job tracking document
    await SchedulerJob.findByIdAndDelete(job._id);

    return res.status(200).json({
      success: true,
      message: `Successfully discarded scheduler job draft and reverted project scheduling states.`
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Lists all past scheduler jobs.
 * Route: GET /api/v1/admin/scheduler/jobs
 */
export const getSchedulerJobs = async (req, res, next) => {
  try {
    const jobs = await SchedulerJob.find({})
      .sort({ createdAt: -1 });

    return res.status(200).json({
      success: true,
      data: jobs
    });
  } catch (error) {
    next(error);
  }
};
